name: Build and Push Backend

on:
  push:
    branches: [ main ]

env:
  REGISTRY: docker.io

jobs:
  build-backend:
    runs-on: ubuntu-latest
    outputs:
      backend-image-tag: ${{ steps.set-tag.outputs.tag }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Set tag
      id: set-tag
      run: |
        TAG=sha-${GITHUB_SHA::8}
        echo "TAG=$TAG" >> $GITHUB_ENV
        echo "tag=$TAG" >> $GITHUB_OUTPUT
        echo "$TAG" > backend_tag.txt

    - name: Upload backend tag artifact
      uses: actions/upload-artifact@v4
      with:
        name: backend-tag
        path: backend_tag.txt

    - name: Build and push backend
      env:
        TAG: ${{ env.TAG }}
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      run: |
        docker build -t $REGISTRY/${DOCKER_HUB_USERNAME}/backendfinal:${TAG} -f backend/Dockerfile .
        docker push $REGISTRY/${DOCKER_HUB_USERNAME}/backendfinal:${TAG}